Stats api url env token
suggestionsbot/suggestions-bot-js pull request #40
Opened 2022-01-17 07:28 UTC by alanlichen

Add new stats api url env token for bot's voting server

2022-01-17 18:58 UTC, alanlichen commented
@acollierr17 Ready for review

2022-01-17 21:53 UTC, acollierr17 commented on .env.example
> +# This is the URL to your instance of the bot's voting server
This comment should probably be "the API endpoint where the guild count is posted" because this URL isn't a prefix, but at this time, it's the _exact_ endpoint for stats (which is `/api/v1/guilds`).

2022-01-17 21:54 UTC, acollierr17 requested changes
Looks good other than one comment/change requested.

2022-01-18 01:35 UTC, acollierr17 approved these changes

2022-01-18 01:35 UTC, merged